# Generated by Django 2.2.25 on 2022-05-10 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20220510_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='apartment',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
