# Generated by Django 2.2.25 on 2022-05-12 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_auto_20220512_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
