# Generated by Django 2.2.25 on 2022-05-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_auto_20220513_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='image_path',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
